.TH "BadEndScene" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BadEndScene \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.PP
\fBScene\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBBadEndScene\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBclean_up\fP ()"
.br
.ti -1c
.RI "virtual void \fBdo_event\fP ()"
.br
.ti -1c
.RI "virtual void \fBshow\fP ()"
.br
.in -1c
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "\fBBadEndScene::BadEndScene\fP ()"
.SH "멤버 함수 문서화"
.PP 
.SS "void \fBBadEndScene::clean_up\fP ()\fC [virtual]\fP"
.PP
\fBScene\fP(으)로부터 재구현되었습니다\&.
.SS "void \fBBadEndScene::do_event\fP ()\fC [virtual]\fP"
.PP
\fBScene\fP(으)로부터 재구현되었습니다\&.
.SS "void \fBBadEndScene::init\fP ()\fC [virtual]\fP"
.PP
\fBScene\fP(으)로부터 재구현되었습니다\&.
.SS "void \fBBadEndScene::show\fP ()\fC [virtual]\fP"
.PP
\fBScene\fP(으)로부터 재구현되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
