.TH "Card" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Card\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCard\fP (int credit_limit, int gage)"
.br
.ti -1c
.RI "std::string \fBprint\fP ()"
.br
.in -1c
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "\fBCard::Card\fP (intcredit_limit, intgage)"
.SH "멤버 함수 문서화"
.PP 
.SS "std::string \fBCard::print\fP ()"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
