.TH "character.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
character.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'collider\&.h'\fP
.br
\fC#include 'CPlayer\&.h'\fP
.br
\fC#include 'Constants\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBCharacter\fP"
.br
.ti -1c
.RI "class \fBHero\fP"
.br
.ti -1c
.RI "class \fBGang\fP"
.br
.in -1c
.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fB_MEJECTY_CHAR_H__\fP"
.br
.in -1c
.SS "변수"

.in +1c
.ti -1c
.RI "const int \fBDOWN\fP = 0"
.br
.ti -1c
.RI "const int \fBLEFT\fP = 1"
.br
.ti -1c
.RI "const int \fBRIGHT\fP = 2"
.br
.ti -1c
.RI "const int \fBUP\fP = 3"
.br
.ti -1c
.RI "const int \fBSTOP\fP = 4"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define \fB_MEJECTY_CHAR_H__\fP"
.SH "변수 문서화"
.PP 
.SS "const int \fBDOWN\fP = 0"
.SS "const int \fBLEFT\fP = 1"
.SS "const int \fBRIGHT\fP = 2"
.SS "const int \fBSTOP\fP = 4"
.SS "const int \fBUP\fP = 3"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
