.TH "Configuration.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration.h \- 
.SH SYNOPSIS
.br
.PP
.SS "변수"

.in +1c
.ti -1c
.RI "const int \fBSCREEN_WIDTH\fP = 640"
.br
.ti -1c
.RI "const int \fBSCREEN_HEIGHT\fP = 480"
.br
.ti -1c
.RI "const int \fBSCREEN_BPP\fP = 32"
.br
.ti -1c
.RI "const int \fBBAR_WIDTH\fP = 150"
.br
.ti -1c
.RI "const int \fBBAR_HEIGHT\fP = \fBSCREEN_HEIGHT\fP"
.br
.ti -1c
.RI "const int \fBMAP_WIDTH\fP = 490"
.br
.ti -1c
.RI "const int \fBMAP_HEIGHT\fP = \fBSCREEN_HEIGHT\fP"
.br
.ti -1c
.RI "const int \fBCHAR_VELOCITY\fP = 15"
.br
.ti -1c
.RI "bool \fBIS_FULL_SCREEN\fP"
.br
.ti -1c
.RI "int \fBDEFAULT_FRAME_RATE\fP"
.br
.ti -1c
.RI "double \fBDEFAULT_RATE\fP"
.br
.ti -1c
.RI "double \fBRATE_RATE\fP"
.br
.ti -1c
.RI "int \fBDEFAULT_LIMIT\fP"
.br
.ti -1c
.RI "int \fBLIMIT_RATE\fP"
.br
.ti -1c
.RI "int \fBSTART_GRADE\fP"
.br
.in -1c
.SH "변수 문서화"
.PP 
.SS "const int \fBBAR_HEIGHT\fP = \fBSCREEN_HEIGHT\fP"
.SS "const int \fBBAR_WIDTH\fP = 150"
.SS "const int \fBCHAR_VELOCITY\fP = 15"
.SS "int \fBDEFAULT_FRAME_RATE\fP"
.SS "int \fBDEFAULT_LIMIT\fP"
.SS "double \fBDEFAULT_RATE\fP"
.SS "bool \fBIS_FULL_SCREEN\fP"
.SS "int \fBLIMIT_RATE\fP"
.SS "const int \fBMAP_HEIGHT\fP = \fBSCREEN_HEIGHT\fP"
.SS "const int \fBMAP_WIDTH\fP = 490"
.SS "double \fBRATE_RATE\fP"
.SS "const int \fBSCREEN_BPP\fP = 32"
.SS "const int \fBSCREEN_HEIGHT\fP = 480"
.SS "const int \fBSCREEN_WIDTH\fP = 640"
.SS "int \fBSTART_GRADE\fP"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
