.TH "Constants.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constants.h \- 
.SH SYNOPSIS
.br
.PP
.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fBMAX_CARD_NAME\fP   20+1"
.br
.ti -1c
.RI "#define \fBMAX_PLAYER_NAME_LEN\fP   10"
.br
.ti -1c
.RI "#define \fBRANK_MAX_COUNT\fP   10"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBERank\fP { \fBeFirstRank\fP =  0, \fBeSecondRank\fP, \fBeThirdRank\fP, \fBeMaxRank\fP }"
.br
.ti -1c
.RI "enum \fBECard\fP { \fBeCardNon\fP =  0, \fBeCardVissa\fP, \fBeCardMister\fP, \fBeCardAmerican\fP, \fBeCardUnion\fP, \fBeCardJHT\fP, \fBeCardDC\fP, \fBeCardMax\fP }"
.br
.ti -1c
.RI "enum \fBENonBanking\fP { \fBeNoBanking\fP =  0, \fBeNonOneCash\fP, \fBeNonSaWa\fP, \fBeNonCashRush\fP, \fBeNonCowCow\fP, \fBeNonMax\fP }"
.br
.ti -1c
.RI "enum \fBEPrivateLoan\fP { \fBePrivateNon\fP = 0, \fBePrivateMafia\fP, \fBePrivateYakuza\fP, \fBePrivateGang\fP, \fBePrivateMax\fP }"
.br
.in -1c
.SS "변수"

.in +1c
.ti -1c
.RI "const char \fBgRankName\fP [\fBeMaxRank\fP][\fBMAX_CARD_NAME\fP]"
.br
.ti -1c
.RI "const char \fBgCardName\fP [\fBeCardMax\fP][\fBMAX_CARD_NAME\fP]"
.br
.ti -1c
.RI "const char \fBgNonBankingName\fP [\fBeNonMax\fP][\fBMAX_CARD_NAME\fP]"
.br
.ti -1c
.RI "const char \fBgPrivateLoanName\fP [\fBePrivateMax\fP][\fBMAX_CARD_NAME\fP]"
.br
.ti -1c
.RI "const char \fBgGradeName\fP [13][2+1]"
.br
.ti -1c
.RI "const char \fBScene_Name\fP [5][16]"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define \fBMAX_CARD_NAME\fP   20+1"
.SS "#define \fBMAX_PLAYER_NAME_LEN\fP   10"
.SS "#define \fBRANK_MAX_COUNT\fP   10"
.SH "열거형 타입 문서화"
.PP 
.SS "enum \fBECard\fP"
.PP
\fB열거형 멤버: \fP
.in +1c
.TP
\fB\fIeCardNon \fP\fP
.TP
\fB\fIeCardVissa \fP\fP
.TP
\fB\fIeCardMister \fP\fP
.TP
\fB\fIeCardAmerican \fP\fP
.TP
\fB\fIeCardUnion \fP\fP
.TP
\fB\fIeCardJHT \fP\fP
.TP
\fB\fIeCardDC \fP\fP
.TP
\fB\fIeCardMax \fP\fP

.SS "enum \fBENonBanking\fP"
.PP
\fB열거형 멤버: \fP
.in +1c
.TP
\fB\fIeNoBanking \fP\fP
.TP
\fB\fIeNonOneCash \fP\fP
.TP
\fB\fIeNonSaWa \fP\fP
.TP
\fB\fIeNonCashRush \fP\fP
.TP
\fB\fIeNonCowCow \fP\fP
.TP
\fB\fIeNonMax \fP\fP

.SS "enum \fBEPrivateLoan\fP"
.PP
\fB열거형 멤버: \fP
.in +1c
.TP
\fB\fIePrivateNon \fP\fP
.TP
\fB\fIePrivateMafia \fP\fP
.TP
\fB\fIePrivateYakuza \fP\fP
.TP
\fB\fIePrivateGang \fP\fP
.TP
\fB\fIePrivateMax \fP\fP

.SS "enum \fBERank\fP"
.PP
\fB열거형 멤버: \fP
.in +1c
.TP
\fB\fIeFirstRank \fP\fP
.TP
\fB\fIeSecondRank \fP\fP
.TP
\fB\fIeThirdRank \fP\fP
.TP
\fB\fIeMaxRank \fP\fP

.SH "변수 문서화"
.PP 
.SS "const char \fBgCardName\fP[\fBeCardMax\fP][\fBMAX_CARD_NAME\fP]"\fB초기값:\fP
.PP
.nf

{
        'No One'
        'Vissa',
        'Mister Card',
        'Ameriacno Espresso',
        'UnionBay',
        'JHT',
        'DCCard'
}
.fi
.SS "const char \fBgGradeName\fP[13][2+1]"\fB초기값:\fP
.PP
.nf

{
        'F',
        'D-',
        'D0',
        'D+',
        'C-',
        'C0',
        'C+',
        'B-',
        'B0',
        'B+',
        'A-',
        'A0',
        'A+'
}
.fi
.SS "const char \fBgNonBankingName\fP[\fBeNonMax\fP][\fBMAX_CARD_NAME\fP]"\fB초기값:\fP
.PP
.nf

{
        'No One',
        'One Cashing',
        'SaWa Money',
        'Cash & Rush',
        'CowCow Finance'
}
.fi
.SS "const char \fBgPrivateLoanName\fP[\fBePrivateMax\fP][\fBMAX_CARD_NAME\fP]"\fB초기값:\fP
.PP
.nf

{
        'No One',
        'Mafia',
        'Yakuza',
        'Gang'
}
.fi
.SS "const char \fBgRankName\fP[\fBeMaxRank\fP][\fBMAX_CARD_NAME\fP]"\fB초기값:\fP
.PP
.nf

{
        'First Financial',
        'Second Financial',
        'Thrid Financial'
}
.fi
.SS "const char \fBScene_Name\fP[5][16]"\fB초기값:\fP
.PP
.nf
 
{
    'START SCENE',
    'GAME SCENE',
    'BAD ENDING',
    'GOOD ENDING',
    'CREDIT SCENE'
}
.fi
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
