.TH "Door" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Door \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <building\&.h>\fP
.PP
\fBCollider\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBDoor\fP (int building_x, int building_y, int _x=\fBDOOR_X\fP, int _y=\fBDOOR_Y\fP, int _w=\fBDOOR_W\fP, int _h=\fBDOOR_H\fP)"
.br
.ti -1c
.RI "virtual bool \fBcheck_collide\fP (\fBCollider\fP *)"
.br
.ti -1c
.RI "virtual SDL_Rect * \fBget_box\fP ()"
.br
.in -1c
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "\fBDoor::Door\fP (intbuilding_x, intbuilding_y, int_x = \fC\fBDOOR_X\fP\fP, int_y = \fC\fBDOOR_Y\fP\fP, int_w = \fC\fBDOOR_W\fP\fP, int_h = \fC\fBDOOR_H\fP\fP)"
.SH "멤버 함수 문서화"
.PP 
.SS "bool \fBDoor::check_collide\fP (\fBCollider\fP *other)\fC [virtual]\fP"
.PP
\fBCollider\fP를 구현\&.
.SS "SDL_Rect * \fBDoor::get_box\fP ()\fC [virtual]\fP"
.PP
\fBCollider\fP를 구현\&.

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
