.TH "GlobalFunctions.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlobalFunctions.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'lua/lua\&.h'\fP
.br

.SS "함수"

.in +1c
.ti -1c
.RI "double \fBGetNonInterestTime\fP (unsigned short pGrade, \fBERank\fP pRank)"
.br
.ti -1c
.RI "double \fBGetRate\fP (unsigned short pGrade, \fBERank\fP pRank)"
.br
.ti -1c
.RI "uint64_t \fBGetGlobalLimit\fP (unsigned short pGrade, \fBERank\fP pRank)"
.br
.ti -1c
.RI "void \fBapply_surface\fP (int x, int y, SDL_Surface *source, SDL_Surface *destination, SDL_Rect *clip=NULL)"
.br
.ti -1c
.RI "SDL_Surface * \fBload_image\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBchange_scene\fP (int scene_num)"
.br
.ti -1c
.RI "void \fBmaj_lua_error\fP (\fBlua_State\fP *, const char *, const char *,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBerror\fP (const char *fmt, const char *at,\&.\&.\&.)"
.br
.in -1c
.SH "함수 문서화"
.PP 
.SS "void \fBapply_surface\fP (intx, inty, SDL_Surface *source, SDL_Surface *destination, SDL_Rect *clip = \fCNULL\fP)"
.SS "void \fBchange_scene\fP (intscene_num)"
.SS "void \fBerror\fP (const char *fmt, const char *at, \&.\&.\&.)"
.SS "uint64_t \fBGetGlobalLimit\fP (unsigned shortpGrade, \fBERank\fPpRank)"
.SS "double \fBGetNonInterestTime\fP (unsigned shortpGrade, \fBERank\fPpRank)"
.SS "double \fBGetRate\fP (unsigned shortpGrade, \fBERank\fPpRank)"
.SS "SDL_Surface* \fBload_image\fP (std::stringfilename)"
.SS "void \fBmaj_lua_error\fP (\fBlua_State\fP *, const char *, const char *, \&.\&.\&.)"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
