.TH "lua_Debug" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_Debug \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lua\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "int \fBevent\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBnamewhat\fP"
.br
.ti -1c
.RI "const char * \fBwhat\fP"
.br
.ti -1c
.RI "const char * \fBsource\fP"
.br
.ti -1c
.RI "int \fBcurrentline\fP"
.br
.ti -1c
.RI "int \fBnups\fP"
.br
.ti -1c
.RI "int \fBlinedefined\fP"
.br
.ti -1c
.RI "int \fBlastlinedefined\fP"
.br
.ti -1c
.RI "char \fBshort_src\fP [\fBLUA_IDSIZE\fP]"
.br
.ti -1c
.RI "int \fBi_ci\fP"
.br
.in -1c
.SH "멤버 데이타 문서화"
.PP 
.SS "int \fBlua_Debug::currentline\fP"
.SS "int \fBlua_Debug::event\fP"
.SS "int \fBlua_Debug::i_ci\fP"
.SS "int \fBlua_Debug::lastlinedefined\fP"
.SS "int \fBlua_Debug::linedefined\fP"
.SS "const char* \fBlua_Debug::name\fP"
.SS "const char* \fBlua_Debug::namewhat\fP"
.SS "int \fBlua_Debug::nups\fP"
.SS "char \fBlua_Debug::short_src\fP[\fBLUA_IDSIZE\fP]"
.SS "const char* \fBlua_Debug::source\fP"
.SS "const char* \fBlua_Debug::what\fP"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
