.TH "lua_glue.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_glue.h \- 
.SH SYNOPSIS
.br
.PP
.SS "함수"

.in +1c
.ti -1c
.RI "void \fBinit_glue\fP ()"
.br
.ti -1c
.RI "void \fBfire_lua_event\fP (int)"
.br
.in -1c
.SH "함수 문서화"
.PP 
.SS "void \fBfire_lua_event\fP (int)"
.SS "void \fBinit_glue\fP ()"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
