.TH "lua_glue.cpp" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_glue.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'Scene\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'lua/lauxlib\&.h'\fP
.br

.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fBLuaGlue\fP   static int"
.br
.in -1c
.SS "함수"

.in +1c
.ti -1c
.RI "\fBLuaGlue\fP \fBlua_p_msg_1\fP (\fBlua_State\fP *)"
.br
.ti -1c
.RI "\fBLuaGlue\fP \fBlua_p_msg_2\fP (\fBlua_State\fP *)"
.br
.ti -1c
.RI "void \fBinit_glue\fP ()"
.br
.ti -1c
.RI "void \fBfire_lua_event\fP (int event_id)"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define \fBLuaGlue\fP   static int"
.SH "함수 문서화"
.PP 
.SS "void \fBfire_lua_event\fP (intevent_id)"
.SS "void \fBinit_glue\fP ()"
.SS "\fBLuaGlue\fP \fBlua_p_msg_1\fP (\fBlua_State\fP *L)"
.SS "\fBLuaGlue\fP \fBlua_p_msg_2\fP (\fBlua_State\fP *L)"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
