.TH "luaL_Buffer" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
luaL_Buffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lauxlib\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "char * \fBp\fP"
.br
.ti -1c
.RI "int \fBlvl\fP"
.br
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "char \fBbuffer\fP [\fBLUAL_BUFFERSIZE\fP]"
.br
.in -1c
.SH "멤버 데이타 문서화"
.PP 
.SS "char \fBluaL_Buffer::buffer\fP[\fBLUAL_BUFFERSIZE\fP]"
.SS "\fBlua_State\fP* \fBluaL_Buffer::L\fP"
.SS "int \fBluaL_Buffer::lvl\fP"
.SS "char* \fBluaL_Buffer::p\fP"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
