.TH "luaL_Reg" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
luaL_Reg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lauxlib\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBlua_CFunction\fP \fBfunc\fP"
.br
.in -1c
.SH "멤버 데이타 문서화"
.PP 
.SS "\fBlua_CFunction\fP \fBluaL_Reg::func\fP"
.SS "const char* \fBluaL_Reg::name\fP"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
