.TH "main.cpp" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GlobalFunctions\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'global\&.h'\fP
.br
\fC#include 'Scene\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'lua_glue\&.h'\fP
.br

.SS "함수"

.in +1c
.ti -1c
.RI "void \fBlua_init\fP ()"
.br
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.ti -1c
.RI "bool \fBload_files\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *args[])"
.br
.ti -1c
.RI "void \fBchange_scene\fP (int scene_num)"
.br
.in -1c
.SS "변수"

.in +1c
.ti -1c
.RI "int \fBDEFAULT_FRAME_RATE\fP"
.br
.ti -1c
.RI "double \fBDEFAULT_RATE\fP"
.br
.ti -1c
.RI "double \fBRATE_RATE\fP"
.br
.ti -1c
.RI "int \fBDEFAULT_LIMIT\fP"
.br
.ti -1c
.RI "int \fBLIMIT_RATE\fP"
.br
.ti -1c
.RI "int \fBSTART_GRADE\fP"
.br
.ti -1c
.RI "bool \fBIS_FULL_SCREEN\fP"
.br
.ti -1c
.RI "\fBScene\fP * \fBscene\fP = NULL"
.br
.ti -1c
.RI "\fBScene\fP * \fBscenes\fP [\fBSCENE_NUM\fP]"
.br
.ti -1c
.RI "TTF_Font * \fBfont\fP = NULL"
.br
.ti -1c
.RI "SDL_Color \fBtextColor\fP = {0,0,0}"
.br
.ti -1c
.RI "SDL_Color \fBwhiteColor\fP = {0xff,0xff,0xff}"
.br
.ti -1c
.RI "SDL_Color \fBblackColor\fP = {0,0,0}"
.br
.ti -1c
.RI "SDL_Surface * \fBbuildings_image\fP"
.br
.ti -1c
.RI "bool \fBquit\fP = false"
.br
.ti -1c
.RI "SDL_Surface * \fBscreen\fP = NULL"
.br
.ti -1c
.RI "SDL_Event \fBevent\fP"
.br
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.in -1c
.SH "함수 문서화"
.PP 
.SS "void \fBchange_scene\fP (intscene_num)"
.SS "void \fBclean_up\fP ()"
.SS "bool \fBinit\fP ()"
.SS "bool \fBload_files\fP ()"
.SS "void \fBlua_init\fP ()"
.SS "int \fBmain\fP (intargc, char *args[])"
.SH "변수 문서화"
.PP 
.SS "SDL_Color \fBblackColor\fP = {0,0,0}"
.SS "SDL_Surface* \fBbuildings_image\fP"
.SS "int \fBDEFAULT_FRAME_RATE\fP"
.SS "int \fBDEFAULT_LIMIT\fP"
.SS "double \fBDEFAULT_RATE\fP"
.SS "SDL_Event \fBevent\fP"
.SS "TTF_Font* \fBfont\fP = NULL"
.SS "bool \fBIS_FULL_SCREEN\fP"
.SS "\fBlua_State\fP* \fBL\fP"
.SS "int \fBLIMIT_RATE\fP"
.SS "bool \fBquit\fP = false"
.SS "double \fBRATE_RATE\fP"
.SS "\fBScene\fP* \fBscene\fP = NULL"
.SS "\fBScene\fP* \fBscenes\fP[\fBSCENE_NUM\fP]"
.SS "SDL_Surface* \fBscreen\fP = NULL"
.SS "int \fBSTART_GRADE\fP"
.SS "SDL_Color \fBtextColor\fP = {0,0,0}"
.SS "SDL_Color \fBwhiteColor\fP = {0xff,0xff,0xff}"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
