.TH "Map" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBinit\fP (SDL_Surface *back)"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "vector< SDL_Rect * > \fBget_boxes\fP ()"
.br
.ti -1c
.RI "vector< \fBBuilding\fP * > \fBget_buildings\fP ()"
.br
.in -1c
.SS "Protected 속성"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "SDL_Surface * \fBbackground\fP"
.br
.ti -1c
.RI "vector< \fBBuilding\fP * > \fBbuildings\fP"
.br
.ti -1c
.RI "vector< SDL_Rect * > \fBboxes\fP"
.br
.ti -1c
.RI "SDL_Rect \fBclip\fP"
.br
.in -1c
.SH "멤버 함수 문서화"
.PP 
.SS "void \fBMap::clean_up\fP ()"
.SS "vector< SDL_Rect * > \fBMap::get_boxes\fP ()"
.SS "vector< \fBBuilding\fP * > \fBMap::get_buildings\fP ()"
.SS "void \fBMap::init\fP (SDL_Surface *back)"
.SS "void \fBMap::show\fP ()"
.SH "멤버 데이타 문서화"
.PP 
.SS "SDL_Surface* \fBMap::background\fP\fC [protected]\fP"
.SS "vector<SDL_Rect*> \fBMap::boxes\fP\fC [protected]\fP"
.SS "vector<\fBBuilding\fP*> \fBMap::buildings\fP\fC [protected]\fP"
.SS "SDL_Rect \fBMap::clip\fP\fC [protected]\fP"
.SS "int \fBMap::h\fP\fC [protected]\fP"
.SS "int \fBMap::w\fP\fC [protected]\fP"
.SS "int \fBMap::x\fP\fC [protected]\fP"
.SS "int \fBMap::y\fP\fC [protected]\fP"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
