.TH "map.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'building\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBMap\fP"
.br
.in -1c
.SS "변수"

.in +1c
.ti -1c
.RI "const int \fBFIRSTBUILDING_NUM\fP = 6"
.br
.ti -1c
.RI "const int \fBSECONDBUILDING_NUM\fP = 4"
.br
.ti -1c
.RI "const int \fBTHIRDBUILDING_NUM\fP = 3"
.br
.in -1c
.SH "변수 문서화"
.PP 
.SS "const int \fBFIRSTBUILDING_NUM\fP = 6"
.SS "const int \fBSECONDBUILDING_NUM\fP = 4"
.SS "const int \fBTHIRDBUILDING_NUM\fP = 3"
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
