.TH "Scene.h" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'character\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'collider\&.h'\fP
.br
\fC#include 'building\&.h'\fP
.br
\fC#include 'map\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'CPlayer\&.h'\fP
.br
\fC#include 'GlobalFunctions\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.ti -1c
.RI "class \fBWalletBar\fP"
.br
.ti -1c
.RI "class \fBTop\fP"
.br
.ti -1c
.RI "class \fBStartScene\fP"
.br
.ti -1c
.RI "class \fBBadEndScene\fP"
.br
.ti -1c
.RI "class \fBGoodEndScene\fP"
.br
.ti -1c
.RI "class \fBCreditScene\fP"
.br
.ti -1c
.RI "class \fBGameScene\fP"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
