.TH "Sprite" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sprite\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBsprite\fP ()"
.br
.in -1c
.SS "Protected 속성"

.in +1c
.ti -1c
.RI "int \fBframe\fP"
.br
.in -1c
.SH "멤버 함수 문서화"
.PP 
.SS "void \fBSprite::sprite\fP ()"
.SH "멤버 데이타 문서화"
.PP 
.SS "int \fBSprite::frame\fP\fC [protected]\fP"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
