.TH "Timer" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBTimer\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBpause\fP ()"
.br
.ti -1c
.RI "void \fBunpause\fP ()"
.br
.ti -1c
.RI "int \fBget_ticks\fP ()"
.br
.ti -1c
.RI "bool \fBis_started\fP ()"
.br
.ti -1c
.RI "bool \fBis_paused\fP ()"
.br
.in -1c
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "\fBTimer::Timer\fP ()"
.SH "멤버 함수 문서화"
.PP 
.SS "int \fBTimer::get_ticks\fP ()"
.SS "bool \fBTimer::is_paused\fP ()"
.SS "bool \fBTimer::is_started\fP ()"
.SS "void \fBTimer::pause\fP ()"
.SS "void \fBTimer::start\fP ()"
.SS "void \fBTimer::stop\fP ()"
.SS "void \fBTimer::unpause\fP ()"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
