.TH "Top" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Top \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBTop\fP (int x, int y, int w, int h)"
.br
.ti -1c
.RI "void \fBshow\fP (SDL_Surface *)"
.br
.ti -1c
.RI "void \fBset_credit_score\fP (int credit)"
.br
.ti -1c
.RI "void \fBset_total_dept\fP (int total)"
.br
.in -1c
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "\fBTop::Top\fP (intx, inty, intw, inth)"
.SH "멤버 함수 문서화"
.PP 
.SS "void \fBTop::set_credit_score\fP (intcredit)"
.SS "void \fBTop::set_total_dept\fP (inttotal)"
.SS "void \fBTop::show\fP (SDL_Surface *background)"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
