.TH "WalletBar" 3 "금 2월 3 2012" "Version test" "Capital Break" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletBar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBinit\fP (int x, int y, int w, int h)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.ti -1c
.RI "void \fBprint_limit\fP (\fBECard\fP, uint64_t)"
.br
.ti -1c
.RI "void \fBshow_gage\fP (\fBECard\fP, float)"
.br
.in -1c
.SH "멤버 함수 문서화"
.PP 
.SS "void \fBWalletBar::clean_up\fP ()"
.SS "void \fBWalletBar::init\fP (intx, inty, intw, inth)"
.SS "void \fBWalletBar::print_limit\fP (\fBECard\fPi, uint64_tmoney)"
.SS "void \fBWalletBar::show\fP ()"
.SS "void \fBWalletBar::show_gage\fP (\fBECard\fPi, floatratio)"

.SH "작성자"
.PP 
소스 코드로부터 Capital Break를 위해 Doxygen에 의해 자동으로 생성됨\&.
